FROM --platform=${BUILDPLATFORM} golang:1.16 AS base
WORKDIR /src
ENV CGO_ENABLED=0
COPY go.* .
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

FROM base AS build
ARG TARGETOS
ARG TARGETARCH
RUN --mount=source=./cmd/agent,target=./cmd/agent \    
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/ ./cmd/agent

FROM golangci/golangci-lint:v1.31.0-alpine AS lint-base

FROM base AS lint
RUN --mount=source=./cmd/agent,target=./cmd/agent \
    --mount=from=lint-base,src=/usr/bin/golangci-lint,target=/usr/bin/golangci-lint \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/root/.cache/golangci-lint \
    golangci-lint run --timeout 10m0s ./cmd/agent/...

FROM scratch AS bin-linux
COPY --from=build /out/agent /agent-Linux-x86_64

FROM scratch AS bin-windows
ARG COMPONENT
COPY --from=build /out/agent.exe /agent-Windows-x86_64.exe

FROM bin-${TARGETOS} as bin
