name: Continuous Integration
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Run linter
        run: make lint
      - 
        name: Build binaries
        run: make bins
      -
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.cert-bootstrapper
          target: image
          push: true
          tags: wyarde/cert-bootstrapper:latest            