name: Continuous Integration
on: [push]
jobs:
  ci_linux:
    name: CI - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build - Linux
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: bin
          platforms: linux
          outputs: bin/
      - name: Build - Windows
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: bin
          platforms: windows
          outputs: bin/
      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Release binaries
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            bin/*
      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Image build - Linux
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          target: runtime-Linux
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: wyarde/cert-bootstrapper:linux

  ci_windows:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: ci_linux
    name: CI - Windows
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: cert-bootstrapper-Windows-x86_64.exe
          out-file-path: bin/
      - name: Login to DockerHub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Image build - Windows
        run: |
          docker build --target runtime-Windows -t wyarde/cert-bootstrapper:nanoserver-1809 .
          docker push wyarde/cert-bootstrapper:nanoserver-1809
      - name: Create Docker manifest
        run: |
          docker manifest create \
            wyarde/cert-bootstrapper:latest 
            --amend wyarde/cert-bootstrapper:linux \
            --amend wyarde/cert-bootstrapper:nanoserver-1809
